FROM ubuntu:22.04 as builder

RUN apt update && apt install -y \
    build-essential cmake \
    protobuf-compiler libprotobuf-dev \
    libboost-all-dev \
    libgtest-dev

WORKDIR /app
COPY . .

RUN mkdir build && cd build && \
    cmake .. && make -j

FROM ubuntu:22.04

RUN apt update && apt install -y \
    libprotobuf-dev \
    libboost-system1.74.0 \
    libgtest-dev

WORKDIR /app

COPY --from=builder /app/build/client .

CMD ["./client"]